services:
  dizambee_api:
    container_name: dizambee_api
    image: dizambee_api
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8300:8080"
    command: npm start
