services:
  dizambee_ui:
    container_name: dizambee_ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8300:3000"
    command: npm start
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8080/api

  dizambee_api:
    container_name: dizambee_api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8301:8080"
    command: npm start

